spring:
  profiles:
    active: a
  data:
    mongodb:
      uri: mongodb://localhost:27017/gowithu
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/gowithu?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: Superzhouqi/15
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
